spring.profiles.default: local
spring.config:
  import:
    - classpath:/jwt.yml
    - classpath:/application-domain.yml

spring:
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  config:
    import: "classpath:jwt.yml"


springdoc:
  package-to-scan: com.simple.study
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    displayRequestDuration: true
    operationsSorter: alpha