spring.profiles.default: local
spring.config:
  import:
    - classpath:/jwt.yml
    - classpath:/application-domain.yml

springdoc:
  package-to-scan: com.simple.study
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    displayRequestDuration: true
    operationsSorter: alpha